### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by 0xO2O** [ChangMM/nanjinglizhi#15]
这样直接上传音频文件，一定涉及到版权的，如果你真的是李志的粉丝，这样做感觉不太妥。他跟哇唧唧哇硬刚了那么久，不就是为了提高大家的版权意识么？

**Comment by afret0** [comment]
先问是不是, 再问为什么...

**Comment by DolorHunter** [comment]
你可以Pull 个新的协议...但是MIT协议其实也足够了

**Comment by terminus1984** [comment]
> 这样直接分享 mp3 的 repo 不相当于是传播盗版么？投诉 GitHub 会直接封掉的吧
> https://2049bbs.xyz/t/1133

@ChangMM 建议了解下github相关政策。同时考虑移除repo中的所有mp3文件，放到云盘吧。真的被举报然后删除了的话，损失就大了。。。

**Comment by ChangMM** [comment]
@terminus1984 👌我把文件给删掉。
